'use client';
import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, ClipboardCheck, Loader2 } from 'lucide-react';
import { api, ApiError } from '@/lib/api';
import { Boton, Modal, SinDatos, useAvisos } from '@/components/ui';
import { confirmarElegante } from '@/components/ui/dialogos';
import { BuscadorSeleccion } from '@/components/ui/BuscadorSeleccion';
export default function Page(){
 const {avisar}=useAvisos();
 const[almacenes,setAlmacenes]=useState<any[]>([]),[conteos,setConteos]=useState<any[]>([]),[almacenId,setAlmacenId]=useState(''),[motivo,setMotivo]=useState('Conteo cíclico'),[ubicaciones,setUbicaciones]=useState<any[]>([]),[ubicacionId,setUbicacionId]=useState('');
 const[tocado,setTocado]=useState(false),[guardando,setGuardando]=useState(false);
 const[captura,setCaptura]=useState<any|null>(null),[cantidades,setCantidades]=useState<Record<string,string>>({});
 const errores=useMemo(()=>({almacenId:!almacenId?'Selecciona un almacén':'',motivo:!motivo.trim()?'El motivo es obligatorio':motivo.trim().length<5?'Describe el motivo con al menos 5 caracteres':''}),[almacenId,motivo]);
 const load=async()=>{const[a,c]=await Promise.all([api.get<any[]>('/catalogo/almacenes'),api.get<any[]>('/catalogo/wms/conteos')]);setAlmacenes(Array.isArray(a)?a:[]);setConteos(Array.isArray(c)?c:[])};
 useEffect(()=>{load().catch(()=>{})},[]);
 useEffect(()=>{if(!almacenId){setUbicaciones([]);setUbicacionId('');return;}api.get<any[]>('/catalogo/wms/ubicaciones',{query:{almacenId}}).then(x=>setUbicaciones(Array.isArray(x)?x:[])).catch(()=>setUbicaciones([]));},[almacenId]);
 const crear=async(e:React.FormEvent)=>{e.preventDefault();setTocado(true);if(Object.values(errores).some(Boolean))return;setGuardando(true);try{await api.post('/catalogo/wms/conteos',{almacenId,ubicacionId:ubicacionId||undefined,motivo:motivo.trim(),conteoCiego:true});setAlmacenId('');setUbicacionId('');setMotivo('Conteo cíclico');setTocado(false);await load();avisar('Conteo ciego abierto y listo para captura.','exito')}catch(e){avisar(e instanceof ApiError?e.mensajeParaPantalla():'No se creó el conteo.','error')}finally{setGuardando(false)}};

 const capturar=async(c:any)=>{try{const completo=await api.get<any>(`/catalogo/wms/conteos/${c.id}`);setCaptura(completo);setCantidades(Object.fromEntries((completo.detalles||[]).map((d:any)=>[d.id,''])));}catch(e){avisar(e instanceof ApiError?e.mensajeParaPantalla():'No se pudo abrir el conteo.','error')}};
 const guardarCaptura=async()=>{if(!captura)return;const detalles=(captura.detalles||[]).map((d:any)=>({detalleId:d.id,cantidad:Number(cantidades[d.id])}));if(detalles.some((d:any)=>!Number.isFinite(d.cantidad)||d.cantidad<0))return avisar('Captura una cantidad válida en todas las posiciones.','alerta');setGuardando(true);try{await api.patch(`/catalogo/wms/conteos/${captura.id}/capturar`,{detalles});setCaptura(null);await load();avisar('Conteo capturado; quedó pendiente de autorización.','exito');}catch(e){avisar(e instanceof ApiError?e.mensajeParaPantalla():'No se pudo capturar.','error')}finally{setGuardando(false)}};
 const cerrar=async(c:any)=>{if(!await confirmarElegante('Se aplicarán las diferencias a la ubicación y lote exactos.',{titulo:`Cerrar ${c.folio}`,peligroso:true}))return;try{await api.patch(`/catalogo/wms/conteos/${c.id}/cerrar`,{});await load();avisar('Conteo cerrado y ajustes aplicados.','exito');}catch(e){avisar(e instanceof ApiError?e.mensajeParaPantalla():'No se pudo cerrar.','error')}};
 return <div className="p-8 max-w-6xl mx-auto space-y-6"><Link href="/dashboard/inventario/transferencias" className="flex gap-2"><ArrowLeft/>Transferencias</Link><h1 className="text-3xl font-black flex gap-3"><ClipboardCheck/>Conteos físicos</h1>
 <form onSubmit={crear} noValidate className="bg-white border rounded-3xl p-6 grid md:grid-cols-[1fr_1fr_2fr_auto] gap-3 items-start"><div><BuscadorSeleccion valor={almacenId} onChange={(id)=>{setAlmacenId(id);setUbicacionId('')}} opciones={almacenes.map(a=>({valor:a.id,etiqueta:a.nombre}))} placeholder="Buscar almacén…"/>{tocado&&errores.almacenId&&<p className="mt-1 text-xs font-semibold text-rose-600">{errores.almacenId}</p>}</div><div><BuscadorSeleccion disabled={!almacenId} valor={ubicacionId} onChange={setUbicacionId} opciones={ubicaciones.map(u=>({valor:u.id,etiqueta:u.codigo}))} placeholder="Todas las ubicaciones"/></div><div><input className={`w-full p-3 border rounded-xl ${tocado&&errores.motivo?'border-rose-400':'border-slate-300'}`} value={motivo} onChange={e=>setMotivo(e.target.value)}/>{tocado&&errores.motivo&&<p className="mt-1 text-xs font-semibold text-rose-600">{errores.motivo}</p>}</div><button disabled={guardando} className="px-6 py-3 bg-slate-900 text-white rounded-xl disabled:opacity-50 flex gap-2 items-center">{guardando&&<Loader2 className="animate-spin" size={18}/>}Abrir conteo ciego</button></form>
 <div className="grid gap-3">{!conteos.length?<SinDatos titulo="No hay conteos abiertos" descripcion="Abre un conteo ciego para iniciar la conciliación física."/>:conteos.map(c=><div key={c.id} className="bg-white border rounded-2xl p-5 flex justify-between"><div><b>{c.folio}</b><p className="text-slate-500">{c.almacen?.nombre} · {c.motivo} · {c.detalles?.length||0} posiciones/lotes</p></div><div className="flex items-center gap-3"><span className="font-bold">{c.estado.replaceAll('_',' ')}</span>{['ABIERTO','EN_CONTEO'].includes(c.estado)&&<button onClick={()=>capturar(c)} className="px-3 py-2 rounded-lg bg-blue-50 text-blue-700 font-bold">Capturar</button>}{c.estado==='PENDIENTE_AUTORIZACION'&&<button onClick={()=>cerrar(c)} className="px-3 py-2 rounded-lg bg-emerald-50 text-emerald-700 font-bold">Cerrar</button>}</div></div>)}</div><Modal abierto={Boolean(captura)} onCerrar={()=>setCaptura(null)} titulo={`Capturar ${captura?.folio??''}`} descripcion="Conteo ciego: captura físicamente cada posición sin mostrar la existencia teórica." ancho={760} pie={<><Boton onClick={()=>setCaptura(null)}>Cancelar</Boton><Boton variante="primario" cargando={guardando} onClick={()=>void guardarCaptura()}>Guardar conteo</Boton></>}>{!captura?.detalles?.length?<SinDatos titulo="El conteo no tiene posiciones"/>:<div className="max-h-[55vh] space-y-3 overflow-y-auto">{captura.detalles.map((d:any)=><div key={d.id} className="grid gap-3 rounded-xl border p-3 md:grid-cols-[1fr_180px]"><div><b>{d.producto?.nombre||'Producto'}</b><p className="text-xs text-slate-500">{d.ubicacion?.codigo||'Sin ubicación'} · {d.lote?.numeroLote||'Sin lote'}</p></div><input className="entrada" type="number" min="0" step="0.0001" placeholder="Cantidad contada" value={cantidades[d.id]??''} onChange={(e)=>setCantidades({...cantidades,[d.id]:e.target.value})}/></div>)}</div>}</Modal></div>}
